graph LR
    id_3325["タニア"]
    id_6329["レイン"]
    id_5887["カナデ"]
    id_8886["アリオス"]
    id_9620["リーン"]
    id_2338["ミナ"]
    id_5953["アッガス"]

    subgraph 冒険者
        id_6329
        id_3325
        id_5887
    end
    subgraph 勇者パーティー
        id_5953
        id_8886
        id_2338
        id_9620
        id_3325
    end

    id_3325 <-->|仲間| id_6329
    id_3325 <-->|仲間| id_5887
    id_3325 -.->.|敵対| id_8886
    id_3325 -.->.|敵対| id_9620
    id_3325 -.->.|敵対| id_2338
    id_3325 -.->.|敵対| id_5953

    style id_3325 fill:#FFD700,stroke:#FF8C00,stroke-width:4px