graph LR
    id_2338["ミナ"]
    id_8886["アリオス"]
    id_9620["リーン"]
    id_5953["アッガス"]
    id_6329["レイン"]

    subgraph 勇者パーティー
        id_5953
        id_2338
        id_9620
        id_8886
    end

    id_2338 <-->|仲間| id_8886
    id_2338 <-->|仲間| id_9620
    id_2338 <-->|仲間| id_5953
    id_2338 <-->|元仲間| id_6329

    style id_2338 fill:#FFD700,stroke:#FF8C00,stroke-width:4px