graph LR
    id_8143["ミナ"]
    id_7582["アリオス"]
    id_3871["リーン"]
    id_9956["レイン"]
    id_1405["タニア"]
    id_8808["カナデ"]

    subgraph 勇者パーティー
        id_3871
        id_7582
        id_8143
    end

    id_8143 <-->|仲間| id_7582
    id_8143 <-->|仲間| id_3871
    id_8143 <-->|元仲間| id_9956
    id_8143 -.->.|新仲間| id_1405
    id_8143 -.->.|新仲間| id_8808

    style id_8143 fill:#FFD700,stroke:#FF8C00,stroke-width:4px