graph LR
    id_1405["タニア"]
    id_8808["カナデ"]
    id_9956["レイン"]
    id_7582["アリオス"]
    id_3871["リーン"]
    id_8143["ミナ"]

    subgraph ビーストテイマー
        id_8808
        id_1405
        id_9956
    end
    subgraph 勇者パーティー
        id_8143
        id_1405
        id_7582
        id_3871
    end

    id_1405 <-->|仲間| id_8808
    id_1405 <-->|主従| id_9956
    id_1405 -.->.|敵| id_7582
    id_1405 -.->.|敵| id_3871
    id_1405 -.->.|敵| id_8143

    style id_1405 fill:#FFD700,stroke:#FF8C00,stroke-width:4px