graph LR
    id_7964["レイン・シュラウド"]
    id_8808["カナデ"]
    id_1405["タニア"]
    id_7582["アリオス"]
    id_8143["ミナ"]
    id_3871["リーン"]

    id_7964 <-->|仲間| id_8808
    id_7964 <-->|仲間| id_1405
    id_7964 -.->.|元仲間| id_7582
    id_7964 -.->.|元仲間| id_8143
    id_7964 -.->.|元仲間| id_3871
    id_7582 -.->.|敵| id_1405
    id_7582 -.->.|敵| id_8808
    id_1405 <-->|友達| id_8808

    style id_7964 fill:#FFD700,stroke:#FF8C00,stroke-width:4px