graph LR
    id_1405["タニア"]
    id_9956["レイン"]
    id_8808["カナデ"]
    id_7582["アリオス"]
    id_3871["リーン"]
    id_8143["ミナ"]
    id_5238["アッガス"]

    subgraph 冒険者パーティー
        id_8808
        id_1405
        id_9956
    end
    subgraph 勇者パーティー
        id_1405
        id_5238
        id_8143
        id_3871
        id_7582
    end

    id_1405 <-->|仲間| id_9956
    id_1405 <-->|仲間| id_8808
    id_1405 -.->.|敵対| id_7582
    id_1405 -.->.|敵対| id_3871
    id_1405 -.->.|敵対| id_8143
    id_1405 -.->.|敵対| id_5238

    style id_1405 fill:#FFD700,stroke:#FF8C00,stroke-width:4px